export const cuisineKeywords = [
  "african",
  "american",
  "argentinian",
  "asian",
  "bangladeshi",
  "brazilian",
  "british",
  "cajun",
  "caribbean",
  "chinese",
  "colombian",
  "cuban",
  "eastern european",
  "egyptian",
  "ethiopian",
  "filipino",
  "french",
  "german",
  "greek",
  "hawaiian",
  "indian",
  "indonesian",
  "irish",
  "israeli",
  "italian",
  "jamaican",
  "japanese",
  "jewish",
  "korean",
  "laotian",
  "latin american",
  "lebanese",
  "malaysian",
  "mediterranean",
  "mexican",
  "middle eastern",
  "moroccan",
  "nepalese",
  "pakistani",
  "peruvian",
  "polish",
  "portuguese",
  "russian",
  "southern",
  "spanish",
  "sri lankan",
  "swedish",
  "syrian",
  "taiwanese",
  "thai",
  "turkish",
  "ukrainian",
  "venezuelan",
  "vietnamese",
  "west african",
];

export const dietaryTagKeywords = [
  "fodmap",
  "alkaline",
  "anti-inflammatory",
  "clean eating",
  "dairy-free",
  "diabetic",
  "egg-free",
  "gluten-free",
  "halal",
  "heart-healthy",
  "high-fiber",
  "high-protein",
  "kosher",
  "keto",
  "low-calorie",
  "low-carb",
  "low-cholesterol",
  "low-fat",
  "low-sodium",
  "nut-free",
  "paleo",
  "peanut-free",
  "plant-based",
  "pregnancy-safe",
  "raw",
  "soy-free",
  "sugar-free",
  "vegan",
  "vegetarian",
  "weight watchers",
  "whole30",
];

export const healthTags = [
  "diabetic",
  "keto",
  "low-carb",
  "low sugar",
  "low sodium",
  "low fat",
  "low calorie",
  "high-protein",
  "high fiber",
  "heart-healthy",
  "weight loss",
  "low cholesterol",
  "high cholesterol",
  "low glycemic",
  "gluten-free",
  "paleo",
  "dash diet",
  "whole30",
  "anti-inflammatory",
  "renal-friendly",
  "liver-friendly",
  "gut-friendly",
  "fodmap",
  "low purine",
  "PCOS-friendly",
  "thyroid-friendly",
  "anemia-friendly",
  "bone health",
  "immunity boost",
  "energy boosting",
];

export const mealTypeKeywords = [
  "breakfast",
  "brunch",
  "lunch",
  "dinner",
  "snack",
  "appetizer",
  "side dish",
  "dessert",
  "beverage",
  "soup",
  "salad",
  "main course",
  "entree",
  "finger food",
  "quick meal",
  "slow cooker",
  "one-pot",
  "grill",
  "bake",
  "roast",
];

export const cookingMethodKeywords = [
  "baking",
  "grilling",
  "roasting",
  "steaming",
  "boiling",
  "frying",
  "sautéing",
  "poaching",
  "braising",
  "broiling",
  "slow cooking",
  "pressure cooking",
  "stir-frying",
  "smoking",
  "searing",
  "thermomix",
  "air frying",
  "sous vide",
  "no cook",
  "no bake",
];

export const difficultyKeywords = ["easy", "medium", "hard"];

export const timeKeywords = [
  "under 15 minutes",
  "under 30 minutes",
  "under 45 minutes",
  "under 1 hour",
  "1-2 hours",
  "over 2 hours",
];

export const equipmentKeywords = [
  "oven",
  "stove",
  "microwave",
  "blender",
  "food processor",
  "slow cooker",
  "instant pot",
  "air fryer",
  "grill",
  "baking dish",
  "mixing bowl",
  "whisk",
  "knife",
  "cutting board",
  "measuring cups",
  "measuring spoons",
  "saucepan",
  "frying pan",
  "baking sheet",
  "colander",
];