export const cuisineKeywords = [
  "african",
  "american",
  "argentinian",
  "asian",
  "bangladeshi",
  "brazilian",
  "british",
  "cajun",
  "caribbean",
  "chinese",
  "colombian",
  "cuban",
  "eastern european",
  "egyptian",
  "ethiopian",
  "filipino",
  "french",
  "german",
  "greek",
  "hawaiian",
  "indian",
  "indonesian",
  "irish",
  "israeli",
  "italian",
  "jamaican",
  "japanese",
  "jewish",
  "korean",
  "laotian",
  "latin american",
  "lebanese",
  "malaysian",
  "mediterranean",
  "mexican",
  "middle eastern",
  "moroccan",
  "nepalese",
  "pakistani",
  "peruvian",
  "polish",
  "portuguese",
  "russian",
  "southern",
  "spanish",
  "sri lankan",
  "swedish",
  "syrian",
  "taiwanese",
  "thai",
  "turkish",
  "ukrainian",
  "venezuelan",
  "vietnamese",
  "west african",
];

export const dietaryTagKeywords = [
  "fodmap",
  "alkaline",
  "anti-inflammatory",
  "clean eating",
  "dairy-free",
  "diabetic",
  "egg-free",
  "gluten-free",
  "halal",
  "heart-healthy",
  "high-fiber",
  "high-protein",
  "kosher",
  "keto",
  "low-calorie",
  "low-carb",
  "low-cholesterol",
  "low-fat",
  "low-sodium",
  "nut-free",
  "paleo",
  "peanut-free",
  "plant-based",
  "pregnancy-safe",
  "raw",
  "soy-free",
  "sugar-free",
  "vegan",
  "vegetarian",
  "weight watchers",
  "whole30",
];

export const healthTags = [
  "diabetic",
  "keto",
  "low-carb",
  "low sugar",
  "low sodium",
  "low fat",
  "low calorie",
  "high-protein",
  "high fiber",
  "heart-healthy",
  "weight loss",
  "low cholesterol",
  "high cholesterol",
  "low glycemic",
  "gluten-free",
  "paleo",
  "dash diet",
  "whole30",
  "anti-inflammatory",
  "renal-friendly",
  "liver-friendly",
  "gut-friendly",
  "fodmap",
  "low purine",
  "PCOS-friendly",
  "thyroid-friendly",
  "anemia-friendly",
  "bone health",
  "immunity boost",
  "energy boosting",
];

// export const healthPromptDescriptions: Record<string, string> = {
//   diabetic: "very low sugar, moderate carbs",
//   keto: "low carbs, moderate fat, low sugar",
//   "low-carb": "low carbohydrates, low sugar",
//   "high-protein": "high protein, moderate fat, low carbs",
//   "heart-healthy": "low sodium and low fat",
//   "weight loss": "low calories and carbs, high fiber and protein",
//   "high fiber": "high fiber, moderate calories",
//   "low sugar": "minimal sugar content",
//   "low sodium": "very low salt content",
//   "low fat": "low fat content",
//   "low cholesterol": "low cholesterol and saturated fat",
//   fodmap: "avoid onions, garlic, wheat, lactose, legumes, and other fermentable carbs",
//   "gut-friendly": "easily digestible, avoids known irritants",
//   "low purine": "low purine content, good for managing gout",
//   "anemia-friendly": "rich in iron and vitamin C",
//   "calcium-rich": "high in calcium for bone health",
//   "immunity boost": "rich in vitamin C, zinc, and antioxidants",
// };